language: node_js
node_js:
  - '6'
install:
  - npm install
script:
  - npm run build
before_install:
  - openssl aes-256-cbc -K $encrypted_bc4f885d0b5f_key -iv $encrypted_bc4f885d0b5f_iv
    -in deploy_key.pem.enc -out deploy_key.pem -d
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy https://github.com/daybrush/daybrush.github.io.git
  - git push deploy
