language: node_js
node_js:
- stable
install:
- npm install
script:
- bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "6f5f9b467f98"
  - COMMIT_AUTHOR_EMAIL: "you@exmaple.com"
cache:
  directories:
    - node_modules