language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_6f5f9b467f98_key -iv $encrypted_6f5f9b467f98_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- git remote add deploy https://github.com/daybrush/daybrush.github.io.git
- git push deploy
